print("enter the age and the program wil send messige which is higher")
number1 = int(input("enter first age:"))
number2 = int(input("enter secound age:"))
print(number1)
print(number2)
print("age 1 is more than age 2")
print(number1>number2)
print("age 2 is more than gae 1")
print(number2>number1)
print("age 1 = age 2")
print(number1=number2)