print("SETING START:lets make dialogui, you need to make frendship, lets start!")
print("SETING START:and you can ask me questions before we start")
print("SETING START:any questions?")
d0 = input("you:")
print(d0)
print("SETING START:ok idk")
print("SETING START:LETS START")
print("FUTURE FRIEND:hello")
d1 =input("you:")
print(d1)
print("FUTURE FRIEND:my name is...")
print("FUTURE FRIEND:by the way you dont need to know my name")
print("FUTURE FRIEND:what is your name mate?")
d2 = input("you:")
print(d2)
print("FUTURE FRIEND:nice to meet you :)")
print("FUTURE FRIEND:where are you from?")
d3 = input("you:")
print(d3)
print("FUTURE FRIEND:eeem... country or a state?")
d4 = input("you:")
print(d4)
print("FUTURE FRIEND:ok.. ok..")
print("FUTURE FRIEND:and what is your hoby?")
d5 = input("you:")
print(d5)
print("FUTURE FRIEND:cool i like that too")
print("FUTURE FRIEND:ok now i trust you and i can tell you my name do you want to know?")
d6 = input("you:")
print(d6)
print("FUTURE FRIEND:ok my name is XUAN")
print("xuan:well i think we are friends now and we have great friendship :)")
print("xuan:riht?...")
d7 = input("you:")
print(d7)
print("xuan: ok i need to go, maby i see you in other homeworks. bye bye :)")