print("ჩაწერე ნებისმიერი რიცხვი/ციფრი")
number1 = int(input("1--->:"))
number2 = int(input("2--->:"))
number3 = int(input("3--->:"))

print(number1 + number2)
print(number1 * number2)
print(number2 + number1 * number3)
print(number1 * number2 * number3)
print(number1 ** number2 + number3)
print(number1 + number2 ** number3)
print(number1 / number2 ** number3)
print(number1 / number2 * number3)
print(number1 // number2 ** number3)
print(number1 // number2 * number3)
print(number1 / number2 + number3)
print(number1 // number2 + number3)
print(number1 * number2 / number3)
print(number1 * number2 // number3)
print(number1 + number2 / number3)
print(number1 + number2 // number3)
print(number1 + number3 ** number2)