print(False and True)
print(False and False)
print(True and True)
print(True and False)
print(True and False)
print(2)
print(True or False)
print(False or True)
print(True or True)
print(False or False)
print(False and True)
